[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "uniPort"
authors = [{name = "Kai Cao", email = "caokai@amss.ac.cn"}]
dynamic = ["version", "description"]
